name: clean_structure_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  dio: ^5.4.0
  jiffy: ^6.2.1
  cached_network_image: ^3.3.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  get_it: ^7.6.4
  path_provider: ^2.1.1
  flutter_screenutil: ^5.9.0
  intl: 0.19.0
  flutter_html: ^3.0.0-alpha.6
  syncfusion_flutter_charts: ^23.2.7
  currency_text_input_formatter: ^2.1.13

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  lint: ^2.2.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/images/
    - assets/icons/
