name: clean_structure_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_dotenv: ^5.0.2
  get: ^4.6.5
  dio: ^5.1.2
  jiffy: ^6.1.0
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  get_it: ^7.6.0
  path_provider: ^2.0.15
  flutter_screenutil: ^5.8.1
  intl: ^0.18.1
  flutter_html: ^3.0.0-alpha.6
  syncfusion_flutter_charts: ^21.2.5
  go_router: ^7.0.1
  currency_text_input_formatter: ^2.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  lint: ^2.1.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  freezed: ^2.3.4
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
